<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="UsersDisplay.aspx.cs" MasterPageFile="~/Site.Master" Inherits="SelfServiceAdminstration.UsersDisplay" %>

<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
   
<div align="center" style="background-color:Gray; font-size:smaller; color:White; font-family:Verdana">
<table style="width:100%" style="background-color:Gray; font-size:larger; color:White; font-family:Verdana">
     <tbody><tr align="left">
    <td class="style1">
        
        
        <span id="menu1_lbluser" style="font-family:Verdana;font-size:X-Small;">User</span>
        <asp:Label ID="userLabel" runat="server" Text="" Font-Bold=true></asp:Label>
    </td>
    <td align="right" style="color:#333333; font-weight:bold;font-size:x-small">
  
    <a href="SelfServiceLogin.aspx" style="color:#333333;">Logout</a>
   
    </td>
    <td align="left" style="color:#333333; font-weight:bold;font-size:x-small">
    
    
     
   
	</td>
    </tr>
    </tbody></table>
    </div>
    
    <div style="position:absolute; top:150px; left:40%; border-color:Gray; border-style:solid">
    <br />
    Search User:<asp:TextBox ID="TextBox1" runat="server"></asp:TextBox>
    <asp:Button ID="Button1"
        runat="server" Text="Click" onclick="Button1_Click" /> <br />
        <br />
        
        <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" 
            CellPadding="4" ForeColor="#333333" GridLines="None" 
            onrowdatabound="GridView1_RowDataBound" onrowdeleted="GridView1_RowDeleted" 
            onrowdeleting="GridView1_RowDeleting" PageSize="50" AllowPaging="True">
            <AlternatingRowStyle BackColor="White" />
            <EditRowStyle BackColor="#2461BF" />
            <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="#EFF3FB" />
            <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
            <SortedAscendingCellStyle BackColor="#F5F7FB" />
            <SortedAscendingHeaderStyle BackColor="#6D95E1" />
            <SortedDescendingCellStyle BackColor="#E9EBEF" />
            <SortedDescendingHeaderStyle BackColor="#4870BE" />
        </asp:GridView>
    
    </div>
    
</asp:Content>
   